language: swift
cache: cocoapods
podfile: Podfile
before_install: 
- gem install cocoapods
- pod install --repo-update 
xcode_workspace: SocialToDo.xcworkspace
osx_image: xcode9
branches:
  except:
    -protocolOrientedRefactor
